(#1) 드롭다운 버튼 세팅 완료
DSM-SSGP/SSGP-iOS pull request #13
Opened 2021-07-27 16:51 UTC by jangseoyoung

2021-07-28 05:34 UTC, kimxwan0319 requested changes
나머진 자유지만, 나중에 사용성을 위해 `sortList() 를 위 setDropDownButton()에서 호출시키면 더 좋을것같습니다.` 이건 꼭 해주셨으면 해요. 
그리고 어제 보내주신 사진에서 드롭다운 뷰의 글자 정렬이 디자인과 다르게 왼쪽정렬인 이유가 있나요??

2021-07-28 05:34 UTC, kimxwan0319 commented on Sources/Extension/UIButton.swift
> +        self.contentHorizontalAlignment = UIControl.ContentHorizontalAlignment.right
아래 ``self.contentMode = .right`` 와 다른점이 궁금합니다!

2021-07-28 05:34 UTC, kimxwan0319 commented on Sources/Extension/UIButton.swift
> +    func sortList() {
sortList() 를 위 setDropDownButton()에서 호출시키면 더 좋을것같습니다.

2021-07-28 05:34 UTC, kimxwan0319 commented on Sources/Extension/UIButton.swift
>          let dropDown = DropDown()
Then을 사용하시면 아래 코드가 모두 간결해 질 것 같습니다!
```swift
// Ex

let dropDown = DropDown().then {
   $0.backgroundColor = R.color.background()
   $0..textColor = R.color.accentColor()!
                     .
                     .
                     .
}
```

2021-07-28 07:14 UTC, jangseoyoung commented on Sources/Extension/UIButton.swift
> +        self.contentHorizontalAlignment = UIControl.ContentHorizontalAlignment.right
글자를 오른쪽으로 정렬하기 위해서 사용했습니다.
self.contentMode =  .right 도 그 용도를 위해 사용하라고 하신 것 같은데 코드를 실행시켰을 때 적용되지 않아
self.contentHorizontalAlignment = UIControl.ContentHorizontalAlignment.right 코드로 대체하였습니다.

2021-07-28 07:28 UTC, jangseoyoung commented on Sources/Extension/UIButton.swift
> +        self.contentHorizontalAlignment = UIControl.ContentHorizontalAlignment.right
그리고 드롭다운 뷰의 글자 정렬이 왼쪽정렬인 이유는 드롭다운 뷰는 기본적으로 테이블뷰같은 속성을 지니고 있어서 따로 글자를 정렬할 수가 없었습니다. 가운데로 글자 정렬을 하려면 드롭다운 셀을 커스텀하면 될 것 같기도 한데 그렇게 하도록 할까요?

2021-07-28 07:59 UTC, kimxwan0319 commented on Sources/Extension/UIButton.swift
> +        self.contentHorizontalAlignment = UIControl.ContentHorizontalAlignment.right
왼쪽 정렬도 깔끔해 보이긴 해요. 커스텀 하게되면 매우 귀찮은 작없이 될것같으니, 이대로도 좋을것같습니다!

2021-08-03 16:37 UTC, kimxwan0319 approved these changes

2021-08-03 16:38 UTC, merged