🔀 :: (#36) MyPage UI 구현
DSM-SSGP/SSGP-iOS pull request #48
Opened 2021-09-09 08:01 UTC by jangseoyoung

2021-09-09 09:54 UTC, kimxwan0319 commented
UI를 캡쳐해서 PR에 올려주세요!

2021-09-13 04:42 UTC, kimxwan0319 requested changes
리뷰 확인해주세요

2021-09-13 04:42 UTC, kimxwan0319 commented on Sources/View/MyPage/MyPageViewController.swift
> +            print("asdf")
디버깅용이였던것같은데, break로 바꿔주세요!

2021-09-13 04:42 UTC, kimxwan0319 commented on Sources/View/MyPage/MyPageViewController.swift
> +        view.tintColor = .black
위 menuTableView then 블럭의 `$0.sectionIndexColor = .black`와 겹치는 코드 아닌가요??

2021-09-13 04:42 UTC, kimxwan0319 commented on Sources/View/MyPage/MyPageViewController.swift
> +        view.tintColor = .black
그리고, 컬러도 백그라운드 컬러로 수정 부탁드립니다.

2021-09-13 04:42 UTC, kimxwan0319 commented on Sources/View/MyPage/MyPageViewController.swift
> +        cell.selectionStyle = .none
스타일을 아예 없에는것보다 cell쪽 코드에
```swift
override func setSelected(_ selected: Bool, animated: Bool) {
        super.setSelected(selected, animated: animated)
        if selected {
            self.setSelected(false, animated: true)
        }
    }
```
를 추가해서 약간의 애니메이션을 주면 좋을것같아요!

2021-09-13 23:32 UTC, jangseoyoung commented on Sources/View/MyPage/MyPageViewController.swift
> +        view.tintColor = .black
겹치는 코드는 삭제했습니다! 저 view.tintColor = .black은 tableview의 헤더 부분이 디자인에서 검은색이라 디자인을 따랐습니다!

2021-09-14 00:03 UTC, kimxwan0319 reviewed
comment

2021-09-14 00:03 UTC, kimxwan0319 commented on Sources/View/MyPage/MyPageViewController.swift
> +        view.tintColor = .black
아, 백그라운드 컬러가 아니였네요. 하지만 컬러 에셋에 있는 `MyPageSection`컬러인것 같아요😉

2021-09-14 00:03 UTC, kimxwan0319 commented on Sources/View/MyPage/MyPageViewController.swift
> +        view.tintColor = .black
그리고 중복되는 코드로 이 부분을 지우는게 위 `$0.sectionIndexColor = .black`를 지우는것보다 코드 줄 수나 가독성을 봤을때 더 좋은것같은데, `$0.sectionIndexColor = .black`을 지우고 이걸 살리신 이유가 있나요??

2021-09-14 09:56 UTC, kimxwan0319 submitted a review, later dismissed

2021-09-14 09:57 UTC, kimxwan0319 approved these changes

2021-09-14 09:57 UTC, merged